[2020-01-20 12:38:29,880] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: process_replies.send_replies 2020-01-20T07:08:17.355254+00:00 [queued]>
[2020-01-20 12:38:29,887] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: process_replies.send_replies 2020-01-20T07:08:17.355254+00:00 [queued]>
[2020-01-20 12:38:29,887] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-01-20 12:38:29,888] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-01-20 12:38:29,888] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-01-20 12:38:29,895] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): send_replies> on 2020-01-20T07:08:17.355254+00:00
[2020-01-20 12:38:29,897] {standard_task_runner.py:52} INFO - Started process 1672 to run task
[2020-01-20 12:38:29,940] {logging_mixin.py:112} INFO - [2020-01-20 12:38:29,939] {dagbag.py:403} INFO - Filling up the DagBag from /Users/aneeshmakala/Documents/ComputerScience/datascience/hapPy/airflow/dags/process_replies.py
[2020-01-20 12:38:29,959] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: process_replies.send_replies 2020-01-20T07:08:17.355254+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-01-20 12:38:29,972] {python_operator.py:105} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=makalaaneesh18@mail.com
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=process_replies
AIRFLOW_CTX_TASK_ID=send_replies
AIRFLOW_CTX_EXECUTION_DATE=2020-01-20T07:08:17.355254+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2020-01-20T07:08:17.355254+00:00
[2020-01-20 12:38:29,976] {logging_mixin.py:112} INFO - [2020-01-20 12:38:29,976] {base_hook.py:84} INFO - Using connection to: id: mongo_default. Host: mongo, Port: 27017, Schema: None, Login: None, Password: None, extra: None
[2020-01-20 12:39:00,386] {taskinstance.py:1088} ERROR - mongo:27017: [Errno 8] nodename nor servname provided, or not known
Traceback (most recent call last):
  File "/Users/aneeshmakala/Documents/ComputerScience/datascience/venv_datascience/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 955, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/aneeshmakala/Documents/ComputerScience/datascience/venv_datascience/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/Users/aneeshmakala/Documents/ComputerScience/datascience/venv_datascience/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/aneeshmakala/Documents/ComputerScience/datascience/hapPy/bot/tweet_reply.py", line 49, in send_replies
    tweet_docs = _get_top_depressed_tweets(mongo_hook, n)
  File "/Users/aneeshmakala/Documents/ComputerScience/datascience/hapPy/bot/tweet_reply.py", line 13, in _get_top_depressed_tweets
    {'$limit': n}
  File "/Users/aneeshmakala/Documents/ComputerScience/datascience/venv_datascience/lib/python3.7/site-packages/airflow/contrib/hooks/mongo_hook.py", line 112, in aggregate
    return collection.aggregate(aggregate_query, **kwargs)
  File "/Users/aneeshmakala/Documents/ComputerScience/datascience/venv_datascience/lib/python3.7/site-packages/pymongo/collection.py", line 2374, in aggregate
    with self.__database.client._tmp_session(session, close=False) as s:
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/aneeshmakala/Documents/ComputerScience/datascience/venv_datascience/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "/Users/aneeshmakala/Documents/ComputerScience/datascience/venv_datascience/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/aneeshmakala/Documents/ComputerScience/datascience/venv_datascience/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/Users/aneeshmakala/Documents/ComputerScience/datascience/venv_datascience/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/aneeshmakala/Documents/ComputerScience/datascience/venv_datascience/lib/python3.7/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/Users/aneeshmakala/Documents/ComputerScience/datascience/venv_datascience/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno 8] nodename nor servname provided, or not known
[2020-01-20 12:39:00,405] {taskinstance.py:1119} INFO - Marking task as FAILED.
[2020-01-20 12:39:04,965] {logging_mixin.py:112} INFO - [2020-01-20 12:39:04,949] {local_task_job.py:103} INFO - Task exited with return code 1
